// ============================================================================
// CASA TEA - CERTIFICATIONS CONSTANTS (FRONTEND UI)
// ============================================================================

export const CERTIFICATIONS = [
  {
    id: 'iso-22000-2018',
    title: 'Hệ Thống Quản Lý An Toàn Thực Phẩm ISO 22000:2018',
    titleZh: 'ISO 22000:2018 食品安全管理系統認證',
    org: 'Tổ chức Chứng nhận Quốc tế TUV SUD / Bureau Veritas',
    orgZh: 'TUV SUD / 法國必維國際檢驗局認證',
    scope: 'Áp dụng cho toàn bộ quy trình chế biến, sao sấy, đóng gói vô trùng trà thành phẩm',
    scopeZh: '適用於原茶精製加工、熱風烘焙、均質拼配及充氮無菌包裝全流程',
    badge: 'Tiêu Chuẩn Quốc Tế ISO',
    badgeZh: 'ISO 國際管理標準',
    validity: 'Có hiệu lực đến 2027 (Đánh giá giám sát hàng năm)',
    validityZh: '有效期限至 2027 年（每年定期稽核複審）',
    image: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?auto=format&fit=crop&w=1000&q=80',
    icon: 'ShieldCheck',
  },
  {
    id: 'haccp-codex',
    title: 'Phân Tích Mối Nguy & Điểm Kiểm Soát Tới Hạn HACCP Codex Alimentarius',
    titleZh: 'HACCP Codex 危害分析與關鍵控制點認證',
    org: 'Ủy ban Tiêu chuẩn Thực phẩm Quốc tế FAO/WHO Codex',
    orgZh: '聯合國糧農組織與世界衛生組織 FAO/WHO 食品法典委員會',
    scope: 'Kiểm soát 5 điểm CCP then chốt trong chuỗi cung ứng nông sản và sản xuất trà',
    scopeZh: '嚴格控管高山原料採購至成品出廠 5 大核心 CCP 關鍵控制點',
    badge: 'Chứng Nhận An Toàn Thực Phẩm',
    badgeZh: '全球食品安全核心認證',
    validity: 'Đánh giá định kỳ 6 tháng / lần',
    validityZh: '每 6 個月定期進行現場稽核',
    image: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=1000&q=80',
    icon: 'Award',
  },
  {
    id: 'fda-registration',
    title: 'Chứng Nhận Đăng Ký Cơ Sở Thực Phẩm Hoa Kỳ (US FDA Registered)',
    titleZh: '美國食品藥品監督管理局 FDA 企業註冊證書',
    org: 'Cục Quản lý Thực phẩm và Dược phẩm Hoa Kỳ (U.S. FDA)',
    orgZh: '美國食品藥品監督管理局 (U.S. FDA)',
    scope: 'Đủ điều kiện xuất khẩu chính ngạch nguyên liệu trà sang thị trường Mỹ & Bắc Mỹ',
    scopeZh: '具備商業茶葉原料合法出口至美國及北美手搖飲市場之資質規範',
    badge: 'Tiêu Chuẩn Xuất Khẩu Mỹ',
    badgeZh: '符合美國出口法規標準',
    validity: 'Gia hạn đăng ký định kỳ theo niên độ FDA',
    validityZh: '依據美國 FDA 法規每年度定期更新登錄',
    image: 'https://images.unsplash.com/photo-1554469384-e58fac16e23a?auto=format&fit=crop&w=1000&q=80',
    icon: 'Globe2',
  },
  {
    id: 'halal-jakim',
    title: 'Chứng Nhận Chuẩn Hồi Giáo Quốc Tế Halal Certified',
    titleZh: '清真品質保證認證 (Halal Certificate)',
    org: 'Văn phòng Chứng nhận Halal (HCA) / Tiêu chuẩn JAKIM & GCC',
    orgZh: 'Halal 認證委員會 (HCA) / 符合馬來西亞 JAKIM 與海灣 GCC 規範',
    scope: 'Toàn bộ dòng trà lá mộc, trà ướp hoa và bột béo CASA đạt chuẩn Halal thuần chay',
    scopeZh: 'CASA 原葉茶系列、花草拼配茶與植脂末全品項符合純素清真標準',
    badge: 'Thị Trường Toàn Cầu',
    badgeZh: '清真友善國際市場通行證',
    validity: 'Tái chứng nhận hàng năm',
    validityZh: '每年定期由宗教與食品專家實地稽核複驗',
    image: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=1000&q=80',
    icon: 'FileCheck2',
  },
  {
    id: 'vietgap-standard',
    title: 'Quy Trình Thực Hành Nông Nghiệp Tốt VietGAP',
    titleZh: 'VietGAP 良好農業規範認證茶園',
    org: 'Trung tâm Giám định Nông nghiệp & Phát triển Nông thôn',
    orgZh: '農業與農村發展部農產品質量檢驗認證中心',
    scope: '1.200 Hecta nông trường trà búp liên kết tại cao nguyên Bảo Lộc & Cầu Đất',
    scopeZh: '涵蓋保祿高原與球坦產區 1,200 公頃契作高山茶葉原料基地',
    badge: 'Nông Sản Sạch An Toàn',
    badgeZh: '源頭無毒健康契作茶葉',
    validity: 'Giám sát thổ nhưỡng và nguồn nước 3 tháng / lần',
    validityZh: '每季定期檢測土壤重金屬與灌溉水源純淨度',
    image: 'https://images.unsplash.com/photo-1563822249548-9a72b6353cd1?auto=format&fit=crop&w=1000&q=80',
    icon: 'CheckCircle2',
  },
  {
    id: 'coa-lab-testing',
    title: 'Phiếu Kiểm Nghiệm Hóa Lý & Vi Sinh Từng Lô (COA & Heavy Metal Test)',
    titleZh: '每批次出廠檢驗報告 (COA) 與農殘重金屬 SGS 檢驗合格證明',
    org: 'Viện Kiểm nghiệm An toàn Vệ sinh Thực phẩm Quốc gia / SGS / Eurofins',
    orgZh: '國家食品安全檢驗研究院 / 國際 SGS / Eurofins 權威實驗室',
    scope: 'Cung cấp phiếu phân tích COA minh bạch cho từng mẻ xuất xưởng của đối tác F&B',
    scopeZh: '每批出貨隨附完整檢驗分析報告，農殘重金屬嚴格符合國家法規上限',
    badge: 'Minh Bạch Mỗi Lô Hàng',
    badgeZh: '每批次透明可追溯',
    validity: 'Kèm theo từng hợp đồng mua hàng xuất xưởng',
    validityZh: '隨每筆大宗採購合約出具當批專屬最新檢測報告',
    image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1000&q=80',
    icon: 'BadgeCheck',
  },
];

